### ISSUE TITLE
当传入 quitp() 函数的第一项参数为整数时会出现 bug

### ISSUE THREAD

**Issue by wsyhb** [GitPinkRabbit/Testlib-for-Lemons#2]
无论传入的整数参数是什么，得分都会是 0。

原因是 testlib_for_lemons.h 中第 4259 行的 __testlib_quitp() 函数未进行和 4241 行的 __testlib_quitp() 函数同样的修改。

被这个东西坑了许久……

**Comment by GitPinkRabbit** [comment]
@wsyhb 

已在 88f34d54bb23e8a2b5043889ad7197e676ae7cbc 中修复
